name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
           registry: ghcr.io
           username: ${{ github.actor }}
           password: ${{ secrets.GITHUB_TOKEN }}
   
      - run: docker build -t ghcr.io/nikitanan123/python-app:latest .
      - run: docker push ghcr.io/nikitanan123/python-app:latest


  deploy: 
        runs-on: ubuntu-latest
        needs: [build]
        steps: 

          - name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
              registry: ghcr.io
              username: ${{ github.actor }}
              password: ${{ secrets.GITHUB_TOKEN }}

          - run: docker pull ghcr.io/nikitanan123/python-app:latest
          - run: docker run ghcr.io/nikitanan123/python-app:latest    



          - name: Run a one-line script
            run: echo Hello,World

          - name: Run a multi line script
            run:
             echo Add other actions to build,
             echo test, and deploy your project.

